# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 141ca6e9b1f01bda07e4d2118b57e363e880ac384a6114873138c7e21fd215d305847d49956cafd45c556010891c5d57fb592481b002d55eec2b4b7389e6fe90

test:
  secret_key_base: 0b1f6a98a2c552fe7f7cfb30ffef1f73049b5f859f2dba254711e037717265cda6d13bc3c84c840bb2d584347bae2ee0da3ff3190e752ceef42cc6302017e71e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
